### ISSUE TITLE
Penumbra 报错

### ISSUE THREAD

**Issue by qfzpjm159** [MeowZWR/DalamudPlugin#3]
[报错日志.zip](https://github.com/MeowZWR/DalamudPlugin/files/14509420/default.zip)

开始是已启用 Penumbra，但人物没有加载到模组（Mod），后面重装 Penumbra 就开始报错了。

**Comment by MeowZWR** [comment]
嗨，我不是开发者可能无法准确地帮您定位问题。
崩溃日志里似乎提到了骨骼问题，可以先检查一下模组：
在Penumbra模组根目录里移出跟骨骼相关的模组文件夹，或者使用二分法排除更多模组。
（另外可以多备份一份XIVLauncher\Roaming\backups\Penumbra里的配置备份，里面有Penumbra对pluginConfigs的相关备份，但最多保存11份，会循环覆盖。它可以帮助恢复合集、排序和优先级设置。）

**Comment by qfzpjm159** [comment]
没事，解析崩溃日志帮了大忙，我后续抽时间帮我朋友排查一下模组问题，辛苦啦~！
