### ISSUE TITLE
Customize+是不是国服还不能用呢？

### ISSUE THREAD

**Issue by coc202** [MeowZWR/DalamudPlugin#5]
大佬，Customize+是不是国服还不能用啊，安装了链接以及本体，没有原版外国大佬的链接仍然装不上

**Comment by MeowZWR** [comment]
你装的原版还是汉化版，国际服原版不能识别国服玩家。

**Comment by MeowZWR** [comment]
库里的版本国服更新6.5当天就可以用的，如果以前安装的插件图标上打×，就卸载删除了再搜索重新安装。

**Comment by coc202** [comment]
> 库里的版本国服更新6.5当天就可以用的，如果以前安装的插件图标上打×，就卸载删除了再搜索重新安装。

谢谢大佬解答，库里还是找不到，全卸载了重新搜也没有用，不过还好别的库更新了
