### ISSUE TITLE
Artisan会导致游戏崩溃

### ISSUE THREAD

**Issue by zhouhuichen741** [MeowZWR/DalamudPlugin#6]
Artisan安装后打开制作笔记卫月的UI会变形,重新打开卫月的样式编辑器重新选一下可以复原,但是只要打开卫月设置保存一下游戏就会崩溃.

**Comment by MeowZWR** [comment]
上游在国际服也是这个现象，只能尝试非常低技术力地修了下。我只偶尔打开搓下理符，搓完就禁用，没怎么测试。

**Comment by zhouhuichen741** [comment]
可以了,感谢
