### ISSUE TITLE
Penumbra的独立分配报错

### ISSUE THREAD

**Issue by zhouhuichen741** [MeowZWR/DalamudPlugin#7]
设置好独立分配的角色之后重启游戏就会报错然后把独立分配的角色重置
![QQ截图20240430200002](https://github.com/MeowZWR/DalamudPlugin/assets/50648819/2a6273d6-48f1-4528-ad43-8b488f08627b)
![QQ截图20240430200022](https://github.com/MeowZWR/DalamudPlugin/assets/50648819/f7221993-b318-44c2-a4db-99653367ad5e)

**Comment by MeowZWR** [comment]
才看到，是分配给谁了。

**Comment by zhouhuichen741** [comment]
分配给自己的几个号,因为角色的种族不一样,所以用的不一样的合集

**Comment by MeowZWR** [comment]
Penumbra先改回笨办法匹配国服角色了（可能漏了什么特殊字符）。

更新到了测试版1.0.2.7里，如果收不到更新请检查操作：
> 卫月设置里开启“获取插件测试版本”，插件安装器里右键该插件勾选“接收测试版本插件”

**Comment by zhouhuichen741** [comment]
可以了,谢谢
